%% DEMLab - Discrete Element Method Laboratory
%
%% Description
%
%% OOP classes
%
%% Initialization
clc; clearvars; close all;
addpath('algorithms',...
        'analysis',...
        'components',...
        'conditions',...
        'inlet_outlet',...
        'input_output',...
        'interactions',...
        'interactions/force_models',...
        'interactions/heat_transfer_models');
Master().runSimulation();